# Generated by Django 4.2.1 on 2023-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arroz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arroz', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Arroz',
            },
        ),
    ]
