# Generated by Django 4.2.1 on 2023-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arroz',
            options={'verbose_name': 'Arroz', 'verbose_name_plural': 'Arroz'},
        ),
        migrations.AddField(
            model_name='arroz',
            name='descricao',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
