# Generated by Django 4.2.1 on 2023-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0002_alter_arroz_options_arroz_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arroz',
            name='descricao',
        ),
        migrations.AddField(
            model_name='arroz',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Preço por unidade'),
        ),
        migrations.AlterField(
            model_name='arroz',
            name='arroz',
            field=models.IntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
    ]
