# Generated by Django 4.2.1 on 2023-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0003_remove_arroz_descricao_arroz_preco_alter_arroz_arroz'),
    ]

    operations = [
        migrations.AddField(
            model_name='arroz',
            name='nome',
            field=models.CharField(default='Arroz', max_length=255),
        ),
    ]
