# Generated by Django 4.2.1 on 2023-05-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0004_arroz_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=255)),
                ('produto', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Preço por unidade')),
            ],
            options={
                'verbose_name': 'Produtos',
                'verbose_name_plural': 'Produto',
            },
        ),
        migrations.DeleteModel(
            name='Arroz',
        ),
    ]
