# Generated by Django 4.2.1 on 2023-05-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0005_produtos_delete_arroz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arroz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arroz', models.CharField(default='Arroz', editable=False, max_length=255, verbose_name='Nome do produto')),
                ('qtd_arroz', models.IntegerField(verbose_name='Quantidade em estoque:')),
                ('preco_arroz', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco arroz:')),
            ],
            options={
                'verbose_name_plural': 'Produto',
            },
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
