# Generated by Django 4.2.1 on 2023-05-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0006_arroz_delete_produtos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arroz',
            options={'verbose_name_plural': 'Arroz'},
        ),
        migrations.AddField(
            model_name='arroz',
            name='teste',
            field=models.CharField(default='Teste1', max_length=10),
        ),
    ]
