# Generated by Django 4.2.1 on 2023-05-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0007_alter_arroz_options_arroz_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arroz',
            name='teste',
        ),
    ]
