# Generated by Django 4.2.1 on 2023-05-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0008_remove_arroz_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feijao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_feijao', models.CharField(default='Feijão', editable=False, max_length=20, verbose_name='Feijao')),
                ('qtd_feijao', models.IntegerField(verbose_name='Quantidade em estoque:')),
                ('preco_feijao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco feijao:')),
            ],
            options={
                'verbose_name_plural': 'Feijao',
            },
        ),
        migrations.CreateModel(
            name='Refri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_refri', models.CharField(default='Refri', editable=False, max_length=20, verbose_name='Refrigerante')),
                ('qtd_refri', models.IntegerField(verbose_name='Quantidade em estoque:')),
                ('preco_refri', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco refrigerante:')),
            ],
            options={
                'verbose_name_plural': 'Refrigerante',
            },
        ),
    ]
