# Generated by Django 4.2 on 2023-04-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_created=True)),
                ('entrega', models.BooleanField(default=False)),
                ('endereço', models.CharField(max_length=255)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('arroz', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mercearia',
                'verbose_name_plural': 'Mercearia',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_created=True)),
                ('entrega', models.BooleanField(default=False)),
                ('endereço', models.CharField(max_length=255)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mercearia.mercearia')),
            ],
            options={
                'verbose_name': 'Área de Gerência',
                'verbose_name_plural': 'Área de Gerência',
            },
        ),
    ]
