# Generated by Django 4.2 on 2023-04-29 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercearia',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Mercearia'},
        ),
        migrations.AlterField(
            model_name='gerente',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mercearia.mercearia'),
        ),
    ]
