# Generated by Django 4.2 on 2023-05-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0002_alter_mercearia_options_alter_gerente_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercearia',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='mercearia',
            name='feijao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mercearia',
            name='arroz',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
