# Generated by Django 4.2 on 2023-05-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0003_alter_mercearia_options_mercearia_feijao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercearia',
            name='banana',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mercearia',
            name='leite',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mercearia',
            name='maça',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mercearia',
            name='ovos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mercearia',
            name='refrigerante',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mercearia',
            name='refrigerante_sem_açucar',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
