# Generated by Django 4.2 on 2023-05-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0004_mercearia_banana_mercearia_leite_mercearia_maça_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercearia',
            old_name='refrigerante_sem_açucar',
            new_name='Refrigerante sem Açucar',
        ),
        migrations.AlterField(
            model_name='gerente',
            name='endereço',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mercearia',
            name='endereço',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
