# Generated by Django 4.2 on 2023-05-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0005_rename_refrigerante_sem_açucar_mercearia_refrigerante_sem_açucar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='endereço',
            field=models.CharField(blank=True, default='Caso não seja entrega, apague essa mensagem', max_length=255),
        ),
        migrations.AlterField(
            model_name='mercearia',
            name='endereço',
            field=models.CharField(blank=True, default='Caso não seja entrega, apague essa mensagem', max_length=255),
        ),
    ]
