# Generated by Django 4.2 on 2023-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0007_alter_mercearia_arroz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercearia',
            name='arroz',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
