# Generated by Django 4.2 on 2023-05-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0008_alter_mercearia_arroz'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercearia',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mercearia',
            name='data_pedido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mercearia',
            name='endereço',
            field=models.CharField(blank=True, default='Se não for entrega, ignore essa caixa', max_length=255),
        ),
        migrations.DeleteModel(
            name='Gerente',
        ),
    ]
