# Generated by Django 4.2 on 2023-05-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0009_mercearia_preco_alter_mercearia_data_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercearia',
            old_name='nome_cliente',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='mercearia',
            old_name='refrigerante',
            new_name='refri',
        ),
        migrations.RenameField(
            model_name='mercearia',
            old_name='preco',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='mercearia',
            name='Refrigerante sem Açucar',
        ),
        migrations.RemoveField(
            model_name='mercearia',
            name='banana',
        ),
        migrations.RemoveField(
            model_name='mercearia',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='mercearia',
            name='leite',
        ),
        migrations.RemoveField(
            model_name='mercearia',
            name='maça',
        ),
        migrations.RemoveField(
            model_name='mercearia',
            name='ovos',
        ),
    ]
