# Generated by Django 4.2.1 on 2023-05-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercearia', '0010_rename_nome_cliente_mercearia_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercearia',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
